Name: "StrategyName"
Module: "ModuleName"
Class: "StrategyClassName"
Frequency: "10m" # can be added as seconds, minutes, hours etc. The frequency to fetch the data
Parameters:
  ema_period: 100
  rsi_period: 20

Watchlist:
  - ["INR"]
  - ["USD", "EUR"]

Tables:
  - ["table_name_1", 100] # 100 is the number of data points to get from
  - ["table_name_2", 20]

AdditionalTables: # get addtional data required
  - ["table_name_1", ["VIX", "NSE"], 200]

RiskParameters:
  - "Risk_PC": 1
